# Generated by Django 2.2.1 on 2019-09-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('sensorType', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SensorData',
                'ordering': ['timestamp'],
            },
        ),
    ]
