# Generated by Django 2.2.1 on 2019-09-09 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'verbose_name_plural': 'SensorData'},
        ),
        migrations.AddField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
