# Generated by Django 2.2.1 on 2019-09-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20190910_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
